<div class="welcome">
	<div class="background">
	<h1>Bem-vindo! Faça login para ter a melhor experiência no Wooby</h1>
	<div class="cat"></div>
	<h2>Assista à animes e playlists favoritas, e muito mais</h2>
	<div class="okay yeah">Login</div>
	<div class="okay nothing">Agora não</div>
	</div>
</div>

<style type="text/css">
	.welcome{
		position: absolute;
		left: 50%;
		top: 50%;
		background: transparent;
		transform: translate(-50%, -50%);
		color: #fff;
		padding: 5em;
		width: 100%;
		height: 100%;
		text-align: center;
	}

	.welcome .background{
		position: absolute;
		left: 50%;
		top: 50%;
		background: transparent;
		transform: translate(-50%, -50%);
		color: #fff;
		padding: 3em;
		background: #000;
		width: 50%;
	}

	.welcome .background h1{
		width: 100%;
		font-size: 2.3em;
		line-height: 40px;
		position: relative;
		top: -30px;
	}

	.welcome .background h2{
		color: #ddd;
		font-size: 1.5em;
		line-height: 100px;
	}

	.welcome .background .cat{
		background: url(img/sign-in-cat.png) no-repeat center/contain;
    	height: 8rem;
	}

	.welcome .background .okay{
		background-color: #fff;
	    border-radius: .1em;
	    color: #000;
	    min-width: 3em;
	    padding: .5em 1em;
	    text-transform: uppercase;
	    font-size: 1.4em;
	    cursor: pointer;
	    top: 20px;
	    position: relative;
	    margin-top: 10px;
	}

	.welcome .background .nothing{
		color: #fff;
		background: #000;
	}
</style>

<script type="text/javascript">
	let logged = 1;
	$(".nothing").click(function(){
		$(".welcome").hide();
		logged = 0;
		playToogle();
	});
	$(".yeah").click(function(){
		$(".welcome").hide();
		$("#guide-105").css("background", "#fff");
			idbutton = "5";
			navigation_leftbar = "1";
			on_leftbar = "1";
			logged = 0;
			playToogle();
		$.post( "/api/account.php", function( data ) {
				  $( "#app" ).html( data );
		});
	});

document.querySelector('body').addEventListener('keydown', function(event) {
	var tecla = event.keyCode;
	if(logged == 1){
	if(tecla == 27) {
	 closealt();
	}
	}
 	
});

function closealt(){
	$(".welcome").hide();
	logged = 0;
	playToogle();
}
</script>